### PR TITLE
OADP-4254: `snapshot.State == ""` typo

### PR DESCRIPTION
**Pull request by kaovilai**
How container was built: `docker build -f Dockerfile.ubi -t ghcr.io/kaovilai/velero-plugin-for-aws:oadp-1.4-velero-release-1.10-2 --platform=linux/amd64 .`

container image: `quay.io/rhn_engineering_whayutin/oadp-velero-plugin-for-aws-pr51:latest`

Wes showed this image worked against a simple VSL snapshot test.

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

### CODE REVIEW

**Comment by weshayutin** [comment]
testing w/ 
docker pull quay.io/rhn_engineering_whayutin/oadp-velero-plugin-for-aws-pr51:latest

```
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  creationTimestamp: "2024-06-10T19:34:40Z"
  generation: 2
  name: dpa-sample
  namespace: openshift-adp
  resourceVersion: "7018162"
  uid: f46d5d48-6e19-4a80-989b-5fc16713cd4d
spec:
  backupLocations:
  - velero:
      config:
        profile: default
        region: us-west-2
      credential:
        key: cloud
        name: cloud-credentials
      default: true
      objectStorage:
        bucket: cvpbucketuswest2
        prefix: velero
      provider: aws
  configuration:
    nodeAgent:
      enable: true
      uploaderType: kopia
    velero:
      defaultPlugins:
      - kubevirt
      - csi
      - openshift
      - aws
  snapshotLocations:
  - velero:
      config:
        profile: default
        region: us-west-2
      provider: aws
  unsupportedOverrides:
    awsPluginImageFqin: ttl.sh/oadp-velero-plugin-for-aws-pr51:latest
status:
  conditions:
  - lastTransitionTime: "2024-06-10T19:34:40Z"
    message: Reconcile complete
    reason: Complete
    status: "True"
    type: Reconciled
```
```
oc get backup testvslbackup1 -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/resource-timeout: 10m0s
    velero.io/source-cluster-k8s-gitversion: v1.29.5+87992f4
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "29"
  creationTimestamp: "2024-06-10T19:51:05Z"
  generation: 9
  labels:
    velero.io/storage-location: dpa-sample-1
  name: testvslbackup1
  namespace: openshift-adp
  resourceVersion: "7024268"
  uid: 3e252a54-be93-4f03-a10f-8c69eb2d6c7f
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  includedNamespaces:
  - minimal-3csivol
  itemOperationTimeout: 4h0m0s
  snapshotMoveData: false
  storageLocation: dpa-sample-1
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - dpa-sample-1
status:
  backupItemOperationsAttempted: 3
  backupItemOperationsCompleted: 3
  completionTimestamp: "2024-06-10T19:52:32Z"
  csiVolumeSnapshotsAttempted: 3
  csiVolumeSnapshotsCompleted: 3
  expiration: "2024-07-10T19:51:05Z"
  formatVersion: 1.1.0
  hookStatus: {}
  phase: Completed
  progress:
    itemsBackedUp: 55
    totalItems: 55
  startTimestamp: "2024-06-10T19:51:05Z"
  version: 1
  warnings: 1
```
```
apiVersion: velero.io/v1
kind: Restore
metadata:
  creationTimestamp: "2024-06-10T19:54:05Z"
  finalizers:
  - restores.velero.io/external-resources-finalizer
  generation: 7
  name: testvslbackup1
  namespace: openshift-adp
  resourceVersion: "7025669"
  uid: 448f2afb-2010-4fc5-825a-b7d7d1dca276
spec:
  backupName: testvslbackup1
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  - csinodes.storage.k8s.io
  - volumeattachments.storage.k8s.io
  - backuprepositories.velero.io
  hooks: {}
  includedNamespaces:
  - '*'
  itemOperationTimeout: 4h0m0s
  uploaderConfig: {}
status:
  completionTimestamp: "2024-06-10T19:54:17Z"
  hookStatus: {}
  phase: Completed
  progress:
    itemsRestored: 31
    totalItems: 31
  startTimestamp: "2024-06-10T19:54:05Z"
  warnings: 8
```

DETAILS:
https://termbin.com/4196

**Review by weshayutin — APPROVED** [review]
/LGTM

**Comment by weshayutin** [comment]
FYI.. tested on d.s build w/
```
whayutin@thinkdoe:~/OPENSHIFT/git/MIG-INTEGRATION/oadp-operator-test/playbooks$ oc get csv
NAME                   DISPLAY         VERSION   REPLACES   PHASE
oadp-operator.v1.4.0   OADP Operator   1.4.0                Succeeded
whayutin@thinkdoe:~/OPENSHIFT/git/MIG-INTEGRATION/oadp-operator-test/playbooks$ oc version
Client Version: 4.12.0-202301042354.p0.g854f807.assembly.stream-854f807
Kustomize Version: v4.5.7
Server Version: 4.16.0-rc.3
Kubernetes Version: v1.29.5+87992f4
```

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
