### PR TITLE
oadp-1.2: Bump golang.org/x/net v0.17.0

### PR DESCRIPTION
**Pull request by kaovilai**
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

### CODE REVIEW

**Comment by kaovilai** [comment]
fyi retest does not work on travis. we can ignore it

**Comment by mateusoliveira43** [comment]
can we remove travis file to disable it? looking into it, it is seems like a CD, not CI. What is the goal of it?

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]

**Pull request merged**
